name: Python

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  wheel:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2025
            cmake-env:
          - name: Linux x86_64
            os: ubuntu-24.04
            cmake-env:
          - name: Linux aarch64
            os: ubuntu-24.04-arm
            cmake-env:
          - name: macOS universal
            os: macos-15
            cmake-env: _PYTHON_HOST_PLATFORM=macosx_14_0_universal2 ARCHFLAGS="-arch x86_64 -arch arm64" MACOSX_DEPLOYMENT_TARGET=14.0

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Make GCC 14 the default toolchain (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 200
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 200

      - uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - run: python3 ./tools/update_version.py
      - run: pip3 install build pytest
      - run: ${{ matrix.cmake-env }} python3 -m build --wheel
      - run: pip3 install dist/sleipnirgroup_jormungandr-*.whl
        shell: bash
      - run: pytest
        shell: bash

      - uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.name }} wheel
          path: dist

  sdist:
    name: sdist
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - run: python3 ./tools/update_version.py
      - run: pip3 install build
      - run: python3 -m build --sdist

      - uses: actions/upload-artifact@v5
        with:
          name: sdist
          path: dist

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-24.04
    needs: [wheel, sdist]
    if: github.repository_owner == 'SleipnirGroup' && github.ref == 'refs/heads/main'
    environment:
      name: pypi
      url: https://pypi.org/p/sleipnirgroup-jormungandr
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v6
        with:
          path: dist
          pattern: '* wheel'
          merge-multiple: true
      - uses: actions/download-artifact@v6
        with:
          path: dist
          pattern: 'sdist'
          merge-multiple: true
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
