name: Python

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-wheel:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2025
            cmake-env:
          - name: Windows aarch64
            os: windows-11-arm
            cmake-env:
          - name: Linux x86_64
            os: ubuntu-24.04
            cmake-env:
          - name: Linux aarch64
            os: ubuntu-24.04-arm
            cmake-env:
          - name: macOS universal
            os: macos-15
            cmake-env: ARCHFLAGS="-arch arm64 -arch x86_64" MACOSX_DEPLOYMENT_TARGET=14.0

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      # https://github.com/actions/checkout/issues/882
      - run: git fetch --tags --force origin

      - name: Make GCC 14 the default toolchain (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 200
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 200

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.9
        # sccache doesn't work with MSBuild
        if: runner.os != 'Windows'

      - uses: actions/setup-python@v6
        with:
          # Minimum supported Python version
          python-version: 3.12

      - run: python3 ./tools/update_version.py
      - run: pip3 install build
      - run: ${{ matrix.cmake-env }} python3 -m build --wheel

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.name }} wheel
          path: dist

  test-wheel:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2025
            version: "3.12"
          - name: Windows aarch64
            os: windows-11-arm
            version: "3.12"
          - name: Linux x86_64
            os: ubuntu-24.04
            version: "3.12"
          - name: Linux aarch64
            os: ubuntu-24.04-arm
            version: "3.12"
          - name: macOS universal
            os: macos-15
            version: "3.12"

          - name: Windows x86_64
            os: windows-2025
            version: "3.13"
          - name: Windows aarch64
            os: windows-11-arm
            version: "3.13"
          - name: Linux x86_64
            os: ubuntu-24.04
            version: "3.13"
          - name: Linux aarch64
            os: ubuntu-24.04-arm
            version: "3.13"
          - name: macOS universal
            os: macos-15
            version: "3.13"

          - name: Windows x86_64
            os: windows-2025
            version: "3.14"
          - name: Windows aarch64
            os: windows-11-arm
            version: "3.14"
          - name: Linux x86_64
            os: ubuntu-24.04
            version: "3.14"
          - name: Linux aarch64
            os: ubuntu-24.04-arm
            version: "3.14"
          - name: macOS universal
            os: macos-15
            version: "3.14"

    name: Test ${{ matrix.name }} (${{ matrix.version }})
    runs-on: ${{ matrix.os }}
    needs: [build-wheel]
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.version }}

      - uses: actions/download-artifact@v7
        with:
          path: dist
          pattern: '${{ matrix.name }} wheel'

      - run: pip3 install pytest dist/sleipnirgroup_jormungandr-*.whl
        shell: bash
      - run: pytest
        shell: bash

  build-sdist:
    name: sdist
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      # https://github.com/actions/checkout/issues/882
      - run: git fetch --tags --force origin

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - run: python3 ./tools/update_version.py
      - run: pip3 install build
      - run: python3 -m build --sdist

      - uses: actions/upload-artifact@v6
        with:
          name: sdist
          path: dist

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-24.04
    needs: [test-wheel, build-sdist]
    if: github.repository_owner == 'SleipnirGroup' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    environment:
      name: pypi
      url: https://pypi.org/p/sleipnirgroup-jormungandr
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          path: dist
          pattern: '* wheel'
          merge-multiple: true
      - uses: actions/download-artifact@v7
        with:
          path: dist
          pattern: 'sdist'
          merge-multiple: true
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
